services:
    php:
        build:
            context: ./build/docker/php
            dockerfile: Dockerfile/Dockerfile
        container_name: wallet_driver_php83_container
        volumes:
            - ./:/var/wallet-driver/
            - ./build/docker/php/conf/php.ini:/usr/local/etc/php/php.ini
        ports:
            - "9000:9000"
        restart: unless-stopped
        extra_hosts:
            - "host.docker.internal:host-gateway"
        healthcheck:
            test: [ "CMD-SHELL", "pidof php-fpm || exit 1" ]
            interval: 30s
            timeout: 10s
            retries: 3
        networks:
            - WalletDriverNetwork
        deploy:
            mode: global

networks:
    WalletDriverNetwork:
        driver: bridge
        attachable: true
