services:
    php:
        build:
            context: ./build/docker/php
            dockerfile: Dockerfile/Dockerfile
        container_name: database_driver_php83_container
        volumes:
            - ./:/var/database-driver/
            - ./build/docker/php/conf/php.ini:/usr/local/etc/php/php.ini
        ports:
            - "9000:9000"
        restart: unless-stopped
        extra_hosts:
            - "host.docker.internal:host-gateway"
        healthcheck:
            test: [ "CMD-SHELL", "pidof php-fpm || exit 1" ]
            interval: 30s
            timeout: 10s
            retries: 3
        networks:
            - DatabaseDriverNetwork
        deploy:
            mode: global

    mongodb:
        build:
            context: ./build/docker/mongo
            dockerfile: Dockerfile/Dockerfile
        container_name: database_driver_mongodb_container
        restart: always
        ports:
            - "${DB_PORT}:${DB_PORT}"
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
            MONGO_INITDB_DATABASE: ${DB_DATABASE}
        volumes:
            - ./data/mongodb:/data/db
        networks:
            - DatabaseDriverNetwork

networks:
    DatabaseDriverNetwork:
        driver: bridge
        attachable: true
